### PR TITLE
initialize tesseract

### PR DESCRIPTION
**Pull request by ransomw**
this is the simplest demo of tesseract.

so far, the image with overlays is not something tesseract understands.  we might need to do additional image-processing for tesseract to understand output of `Writer`

a lot of what i'm testing here is whether it runs in CI

### CODE REVIEW

**Comment by ransomw** [comment]
it runs in CI!

**Review by gavintranquilino — APPROVED** [review]
i approve
it does indeed return hello world

**Comment by ransomw** [comment]
coolcool.  i'm going to leave this open a little longer to see if people can run the test locally (i.e. there're no problems installing tesseract).  ty for the feedback

**Comment by ransomw** [comment]
there's a **todo** in the README for tesseract installation on Windows

**Pull request merged**
