### PR TITLE
Refactor Writer to have draw box as a separate method.

### PR DESCRIPTION
**Pull request by BautistaDalmasso**
I wrote this for the `proto-text-sub` but it's probably good to just push this now as a separate thing.

### CODE REVIEW

**Comment by BautistaDalmasso** [comment]
BTW, this depends on #22 and I'll probably have to solve the merge conflicts later because I'm dumb.

**Review by ransomw — APPROVED** [review]
i'm approving this to merge b/c i'm going to be afk for part of today and i don't want to impede progress.  watch out for them there merge conflicts! in main the `rectangle` `fill` is `255`.  you probably want that value.

**Review by ransomw — CHANGES_REQUESTED** [review]
actually, i see you've merge and not resolved to `255`

**Comment by BautistaDalmasso** [comment]
Alright, solved the `255` thing, mb @ransomw

**Review by ransomw — APPROVED** [review]
good to go!  i will be around this morning after all, btw

**Pull request merged**
